### ISSUE TITLE
create a gun buyers listing site 

### ISSUE THREAD

**Issue by mahdi-ln** [mahdi-ln/reverse-gun-market#1]
Note: this project is for non-democratic countries only
In some countries, gun sellers hesitate to post ad on markets. In this site,  gun buyers can post their request and sellers can find them based on city.

Face verification will be forced for buyers. So police cannot post too much trap. (Police in rhis counries only care about sellers. They know buyers who show his face only need it for non political or criminal reason and probably use it for revange or suicide)
Instead of face verification, every other method that stops an organization's staff to create multi account can be used)

The trade and chat will be done on a other site this site only list buyers face photo/video and profile id on a third-party market. Ideal market for this purpose can be "Particl Market". 
 
Every buyers will mention his **particl market** identity so if he already made a trade (gun purchase) sellers would ignore him if doesn't know him

 

### Give your price in comment or chat. 
Also, I don't care if you keep ownership of the site.

**Comment by gitpaybot** [comment]
A bounty of *1 usd* was added to this issue. See task on [GitPay](https://gitpay.me/#/task/515)

**Comment by gitpaybot** [comment]
A bounty of *1 usd* was added to this issue. See task on [GitPay](https://gitpay.me/#/task/515)

**Comment by mahdi-ln** [comment]
Update: every buyers will mention his particl market identity so if he already made a trade (gun purchase) sellers would ignore him if doesn't know him

**Comment by gitpaybot** [comment]
Gitpay is an Open Source platform to reward contributors to get things done 💝

[About Gitpay platform](https://gitpay.me).

For portuguese, you can [access the portuguese version](https://github.com/worknenjoy/gitpay-github-app/blob/master/first-comment.pt-br.md)

### 📋 Step by Step

#### If you are the task owner who created this issue
- [x] 🔔 ***Issue open*** an issue was created
- [x] 👌 **Issue added on Gitpay** this issue was added on gitpay [https://gitpay.me/#/task/520](https://gitpay.me/#/task/520)
- [ ] 📝 **Add bounties** A bounty is added to get things done
- [ ] 📝 **Set a deadline** A deadline to finish the task (optional)
- [ ] 💾 **Choose a contributor interested** You can choose someone interested that will be able to solve your issue

#### If you want to contribute and be rewarded
- [ ] 💾 **A contributor is interested** You can show interest on the task page clicking in "I'm interested"
- [ ] 💾 **You can offer** You can make an offer
- [ ] 🔀 **You can be assigned**. You can be assigned, you should work on the task and send a Pull Request.
- [ ] 💬 **Review** Ask in comments for a review :)
- [ ] 🏁 **Approved** Once approved you will receive your payment

### 📋 Task status
- [x] ***OPEN***
- [ ] ***IN PROGRESS***
- [ ] ***DONE***

### Good to know

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. For a more compreenhensive guide to create the Pull Request properly, you can access: https://guides.github.com/activities/hello-world/

3. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)

### 🤔❓ Questions
Leave a comment below!
This issue was a comment made by our GitpayBot [Gitpay Bot](https://github.com/gitpaybot).

**Comment by gitpaybot** [comment]
Gitpay is an Open Source platform to reward contributors to get things done 💝

[About Gitpay platform](https://gitpay.me).

For portuguese, you can [access the portuguese version](https://github.com/worknenjoy/gitpay-github-app/blob/master/first-comment.pt-br.md)

### 📋 Step by Step

#### If you are the task owner who created this issue
- [x] 🔔 ***Issue open*** an issue was created
- [x] 👌 **Issue added on Gitpay** this issue was added on gitpay [https://gitpay.me/#/task/521](https://gitpay.me/#/task/521)
- [ ] 📝 **Add bounties** A bounty is added to get things done
- [ ] 📝 **Set a deadline** A deadline to finish the task (optional)
- [ ] 💾 **Choose a contributor interested** You can choose someone interested that will be able to solve your issue

#### If you want to contribute and be rewarded
- [ ] 💾 **A contributor is interested** You can show interest on the task page clicking in "I'm interested"
- [ ] 💾 **You can offer** You can make an offer
- [ ] 🔀 **You can be assigned**. You can be assigned, you should work on the task and send a Pull Request.
- [ ] 💬 **Review** Ask in comments for a review :)
- [ ] 🏁 **Approved** Once approved you will receive your payment

### 📋 Task status
- [x] ***OPEN***
- [ ] ***IN PROGRESS***
- [ ] ***DONE***

### Good to know

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. For a more compreenhensive guide to create the Pull Request properly, you can access: https://guides.github.com/activities/hello-world/

3. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)

### 🤔❓ Questions
Leave a comment below!
This issue was a comment made by our GitpayBot [Gitpay Bot](https://github.com/gitpaybot).
